language: shell
os: linux
dist: bionic

services:
  - docker

env:
  - WINE_BRANCH=devel
  - WINE_BRANCH=stable

script:
  - bash build

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
